"""Add github_url to candidate profiles

Revision ID: 9efd23365bcb
Revises: d1d08f24d6f8
Create Date: 2026-09-14 22:00:32.991802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efd23365bcb'
down_revision: Union[str, Sequence[str], None] = 'd1d08f24d6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('github_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'github_url')
    # ### end Alembic commands ###
